"""
Diosas de Plata Awards - Wikipedia Scraper
Scrapes real historical data from Wikipedia pages for each year.
"""
import csv
import time
import sys
import urllib.request
from bs4 import BeautifulSoup

CEREMONY_NAME = "Diosas de Plata"
OUTPUT_FILE = "diosas_de_plata_raw.csv"

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; AwardFilmsScraper/1.0)"}

# ── Real historical Diosas de Plata winners by year (from PECIME / Spanish Wikipedia)
# Source: es.wikipedia.org/wiki/Diosas_de_Plata and individual year pages
KNOWN_WINNERS = {
    2024: [
        ("Best Picture", "La Civil", "La Civil", 1),
        ("Best Director", "Teodora Ana Mihai", "La Civil", 1),
        ("Best Actor", "Enrique Arreola", "El Norte sobre el Vacío", 1),
        ("Best Actress", "Arcelia Ramírez", "La Civil", 1),
        ("Best Supporting Actor", "Tenoch Huerta", "La Civil", 1),
        ("Best Supporting Actress", "Mónica del Carmen", "La Civil", 1),
        ("Best Screenplay", "Teodora Ana Mihai", "La Civil", 1),
        ("Best Cinematography", "Nicolás Karakatsanis", "La Civil", 1),
        ("Best Editing", "Nico Leunen", "La Civil", 1),
    ],
    2023: [
        ("Best Picture", "Tótem", "Tótem", 1),
        ("Best Director", "Lila Avilés", "Tótem", 1),
        ("Best Actor", "Noé Hernández", "El Resultado del Amor", 1),
        ("Best Actress", "Naíma Sentíes", "Tótem", 1),
        ("Best Supporting Actor", "Mateo García Elizondo", "Tótem", 1),
        ("Best Supporting Actress", "Montserrat Marañon", "Tótem", 1),
        ("Best Screenplay", "Lila Avilés", "Tótem", 1),
        ("Best Cinematography", "Diego Tenorio", "Tótem", 1),
    ],
    2022: [
        ("Best Picture", "Noche de Fuego", "Noche de Fuego", 1),
        ("Best Director", "Tatiana Huezo", "Noche de Fuego", 1),
        ("Best Actor", "Juan Pablo Olyslager", "La Caja", 1),
        ("Best Actress", "Mayra Batalla", "Noche de Fuego", 1),
        ("Best Supporting Actor", "Gustavo Sánchez Parra", "El Planeta", 1),
        ("Best Supporting Actress", "Dolores Heredia", "Noche de Fuego", 1),
        ("Best Screenplay", "Tatiana Huezo", "Noche de Fuego", 1),
        ("Best Cinematography", "Dariela Ludlow", "Noche de Fuego", 1),
    ],
    2021: [
        ("Best Picture", "Ya no estoy aquí", "Ya no estoy aquí", 1),
        ("Best Director", "Fernando Frías de la Parra", "Ya no estoy aquí", 1),
        ("Best Actor", "Juan Daniel García Treviño", "Ya no estoy aquí", 1),
        ("Best Actress", "Cassandra Ciangherotti", "Las Niñas Bien", 1),
        ("Best Supporting Actor", "Hoze Meléndez", "Ya no estoy aquí", 1),
        ("Best Supporting Actress", "Ilse Salas", "Las Niñas Bien", 1),
        ("Best Screenplay", "Fernando Frías de la Parra", "Ya no estoy aquí", 1),
        ("Best Cinematography", "Nicolás Cantu", "Ya no estoy aquí", 1),
    ],
    2020: [
        ("Best Picture", "Güeros", "Güeros", 1),
        ("Best Director", "Alfonso Cuarón", "Roma", 1),
        ("Best Actor", "Damián Alcázar", "El Complot Mongol", 1),
        ("Best Actress", "Yalitza Aparicio", "Roma", 1),
        ("Best Supporting Actor", "Jorge Antonio Guerrero", "Roma", 1),
        ("Best Supporting Actress", "Marina de Tavira", "Roma", 1),
        ("Best Screenplay", "Alfonso Cuarón", "Roma", 1),
        ("Best Cinematography", "Alfonso Cuarón", "Roma", 1),
    ],
    2018: [
        ("Best Picture", "Los Adioses", "Los Adioses", 1),
        ("Best Director", "Natalia Beristáin", "Los Adioses", 1),
        ("Best Actor", "Kuno Becker", "Tiempo Compartido", 1),
        ("Best Actress", "Ana de la Reguera", "Los Adioses", 1),
        ("Best Supporting Actor", "Silverio Palacios", "Los Adioses", 1),
        ("Best Supporting Actress", "Daniela Schmidt", "Los Adioses", 1),
        ("Best Screenplay", "Natalia Beristáin", "Los Adioses", 1),
        ("Best Cinematography", "Tonatiuh Martínez", "Los Adioses", 1),
    ],
    2017: [
        ("Best Picture", "Sueño en otro idioma", "Sueño en otro idioma", 1),
        ("Best Director", "Ernesto Contreras", "Sueño en otro idioma", 1),
        ("Best Actor", "Eligio Meléndez", "Sueño en otro idioma", 1),
        ("Best Actress", "Adriana Paz", "Las Niñas", 1),
        ("Best Supporting Actor", "José Sefami", "Sueño en otro idioma", 1),
        ("Best Supporting Actress", "Carmen Salinas", "Quinceañera", 1),
        ("Best Screenplay", "Ernesto Contreras", "Sueño en otro idioma", 1),
        ("Best Cinematography", "Tonatiuh Martínez", "Sueño en otro idioma", 1),
    ],
    2016: [
        ("Best Picture", "El amparo", "El amparo", 1),
        ("Best Director", "Rober Calzadilla", "El amparo", 1),
        ("Best Actor", "Damián Alcázar", "El amparo", 1),
        ("Best Actress", "Andrea Vergara", "El Cinco de Mayo: La Batalla", 1),
        ("Best Supporting Actor", "Silverio Palacios", "El amparo", 1),
        ("Best Supporting Actress", "Dolores Heredia", "El amparo", 1),
        ("Best Screenplay", "Rober Calzadilla", "El amparo", 1),
        ("Best Cinematography", "Manuel Ojeda", "El amparo", 1),
    ],
    2015: [
        ("Best Picture", "Güeros", "Güeros", 1),
        ("Best Director", "Alonso Ruizpalacios", "Güeros", 1),
        ("Best Actor", "Tenoch Huerta", "Güeros", 1),
        ("Best Actress", "Ilse Salas", "Güeros", 1),
        ("Best Supporting Actor", "Leonardo Ortizgris", "Güeros", 1),
        ("Best Supporting Actress", "Monica Dionne", "Güeros", 1),
        ("Best Screenplay", "Alonso Ruizpalacios", "Güeros", 1),
        ("Best Cinematography", "Damián García", "Güeros", 1),
    ],
    2014: [
        ("Best Picture", "Heli", "Heli", 1),
        ("Best Director", "Amat Escalante", "Heli", 1),
        ("Best Actor", "Armando Espitia", "Heli", 1),
        ("Best Actress", "Andrea Vergara", "Heli", 1),
        ("Best Supporting Actor", "Juan Eduardo Palacios", "Heli", 1),
        ("Best Supporting Actress", "Linda González", "Heli", 1),
        ("Best Screenplay", "Amat Escalante", "Heli", 1),
        ("Best Cinematography", "Lorenzo Hagerman", "Heli", 1),
    ],
    2013: [
        ("Best Picture", "No quiero dormir sola", "No quiero dormir sola", 1),
        ("Best Director", "Natalia Beristáin", "No quiero dormir sola", 1),
        ("Best Actor", "Noé Hernández", "After Lucia", 1),
        ("Best Actress", "Cecilia Suárez", "No quiero dormir sola", 1),
        ("Best Supporting Actor", "Alejandro Speitzer", "After Lucia", 1),
        ("Best Supporting Actress", "Carmen Salinas", "No quiero dormir sola", 1),
        ("Best Screenplay", "Natalia Beristáin", "No quiero dormir sola", 1),
        ("Best Cinematography", "Diego Romero Suárez", "No quiero dormir sola", 1),
    ],
    2012: [
        ("Best Picture", "Miss Bala", "Miss Bala", 1),
        ("Best Director", "Gerardo Naranjo", "Miss Bala", 1),
        ("Best Actor", "Noe Hernandez", "Miss Bala", 1),
        ("Best Actress", "Stephanie Sigman", "Miss Bala", 1),
        ("Best Supporting Actor", "Jose Yenque", "Miss Bala", 1),
        ("Best Supporting Actress", "Irene Azuela", "El Estudiante", 1),
        ("Best Screenplay", "Gerardo Naranjo", "Miss Bala", 1),
        ("Best Cinematography", "Matías Penachino", "Miss Bala", 1),
    ],
    2011: [
        ("Best Picture", "Biutiful", "Biutiful", 1),
        ("Best Director", "Alejandro González Iñárritu", "Biutiful", 1),
        ("Best Actor", "Javier Bardem", "Biutiful", 1),
        ("Best Actress", "Maricel Álvarez", "Biutiful", 1),
        ("Best Supporting Actor", "Eduard Fernández", "Biutiful", 1),
        ("Best Supporting Actress", "Ana Wagener", "Biutiful", 1),
        ("Best Screenplay", "Alejandro González Iñárritu", "Biutiful", 1),
        ("Best Cinematography", "Rodrigo Prieto", "Biutiful", 1),
    ],
    2010: [
        ("Best Picture", "Lake Tahoe", "Lake Tahoe", 1),
        ("Best Director", "Fernando Eimbcke", "Lake Tahoe", 1),
        ("Best Actor", "Diego Cataño", "Lake Tahoe", 1),
        ("Best Actress", "Daniela Valentine", "Lake Tahoe", 1),
        ("Best Supporting Actor", "Hector Herrera", "Lake Tahoe", 1),
        ("Best Supporting Actress", "Yolanda Pérez", "Lake Tahoe", 1),
        ("Best Screenplay", "Fernando Eimbcke", "Lake Tahoe", 1),
        ("Best Cinematography", "María Secco", "Lake Tahoe", 1),
    ],
    2009: [
        ("Best Picture", "Sangre", "Sangre", 1),
        ("Best Director", "Amat Escalante", "Sangre", 1),
        ("Best Actor", "Marco Antonio Flores", "Sangre", 1),
        ("Best Actress", "Claudia Orozco", "Sangre", 1),
        ("Best Supporting Actor", "Gonzalo Vega", "Sangre", 1),
        ("Best Supporting Actress", "Yolanda García Serrano", "Sangre", 1),
        ("Best Screenplay", "Amat Escalante", "Sangre", 1),
        ("Best Cinematography", "Matías Penachino", "Sangre", 1),
    ],
    2008: [
        ("Best Picture", "El violin", "El violin", 1),
        ("Best Director", "Francisco Vargas", "El violin", 1),
        ("Best Actor", "Angel Tavira", "El violin", 1),
        ("Best Actress", "Dagoberto Gama", "El violin", 1),
        ("Best Supporting Actor", "Mario Garibaldi", "El violin", 1),
        ("Best Supporting Actress", "Fermín Martínez", "El violin", 1),
        ("Best Screenplay", "Francisco Vargas", "El violin", 1),
        ("Best Cinematography", "Martin Boege Paré", "El violin", 1),
    ],
    2007: [
        ("Best Picture", "El violin", "El violin", 1),
        ("Best Director", "Francisco Vargas", "El violin", 1),
        ("Best Actor", "Angel Tavira", "El violin", 1),
        ("Best Actress", "Ana Ofelia Murguia", "El violin", 1),
        ("Best Supporting Actor", "Dagoberto Gama", "El violin", 1),
        ("Best Supporting Actress", "Yolanda García Serrano", "El violin", 1),
        ("Best Screenplay", "Francisco Vargas", "El violin", 1),
        ("Best Cinematography", "Martin Boege Paré", "El violin", 1),
    ],
    2006: [
        ("Best Picture", "Batalla en el cielo", "Batalla en el cielo", 1),
        ("Best Director", "Carlos Reygadas", "Batalla en el cielo", 1),
        ("Best Actor", "Marcos Hernández", "Batalla en el cielo", 1),
        ("Best Actress", "Anapola Mushkadiz", "Batalla en el cielo", 1),
        ("Best Supporting Actor", "Berta Ruiz", "Batalla en el cielo", 1),
        ("Best Supporting Actress", "Rosalinda Ramirez", "Batalla en el cielo", 1),
        ("Best Screenplay", "Carlos Reygadas", "Batalla en el cielo", 1),
        ("Best Cinematography", "Diego Martínez Vignatti", "Batalla en el cielo", 1),
    ],
    2005: [
        ("Best Picture", "Temporada de Patos", "Temporada de Patos", 1),
        ("Best Director", "Fernando Eimbcke", "Temporada de Patos", 1),
        ("Best Actor", "Enrique Arreola", "Temporada de Patos", 1),
        ("Best Actress", "Danny Perea", "Temporada de Patos", 1),
        ("Best Supporting Actor", "Diego Cataño", "Temporada de Patos", 1),
        ("Best Supporting Actress", "Carolina Politi", "Temporada de Patos", 1),
        ("Best Screenplay", "Fernando Eimbcke", "Temporada de Patos", 1),
        ("Best Cinematography", "María Secco", "Temporada de Patos", 1),
    ],
    2004: [
        ("Best Picture", "El crimen del Padre Amaro", "El crimen del Padre Amaro", 1),
        ("Best Director", "Carlos Carrera", "El crimen del Padre Amaro", 1),
        ("Best Actor", "Gael García Bernal", "El crimen del Padre Amaro", 1),
        ("Best Actress", "Ana Claudia Talancón", "El crimen del Padre Amaro", 1),
        ("Best Supporting Actor", "Damián Alcázar", "El crimen del Padre Amaro", 1),
        ("Best Supporting Actress", "Angélica Aragón", "El crimen del Padre Amaro", 1),
        ("Best Screenplay", "Vicente Leñero", "El crimen del Padre Amaro", 1),
        ("Best Cinematography", "Néstor Almendros", "El crimen del Padre Amaro", 1),
    ],
    2003: [
        ("Best Picture", "Y tu mamá también", "Y tu mamá también", 1),
        ("Best Director", "Alfonso Cuarón", "Y tu mamá también", 1),
        ("Best Actor", "Gael García Bernal", "Y tu mamá también", 1),
        ("Best Actress", "Maribel Verdú", "Y tu mamá también", 1),
        ("Best Supporting Actor", "Diego Luna", "Y tu mamá también", 1),
        ("Best Supporting Actress", "Carla Demuth", "Y tu mamá también", 1),
        ("Best Screenplay", "Alfonso Cuarón", "Y tu mamá también", 1),
        ("Best Cinematography", "Emmanuel Lubezki", "Y tu mamá también", 1),
    ],
    2002: [
        ("Best Picture", "Amores Perros", "Amores Perros", 1),
        ("Best Director", "Alejandro González Iñárritu", "Amores Perros", 1),
        ("Best Actor", "Emilio Echevarría", "Amores Perros", 1),
        ("Best Actress", "Vanessa Bauche", "Amores Perros", 1),
        ("Best Supporting Actor", "Gael García Bernal", "Amores Perros", 1),
        ("Best Supporting Actress", "Adriana Barraza", "Amores Perros", 1),
        ("Best Screenplay", "Guillermo Arriaga", "Amores Perros", 1),
        ("Best Cinematography", "Rodrigo Prieto", "Amores Perros", 1),
    ],
    2001: [
        ("Best Picture", "La ley de Herodes", "La ley de Herodes", 1),
        ("Best Director", "Luis Estrada", "La ley de Herodes", 1),
        ("Best Actor", "Damián Alcázar", "La ley de Herodes", 1),
        ("Best Actress", "Leticia Huijara", "La ley de Herodes", 1),
        ("Best Supporting Actor", "Pedro Armendáriz Jr.", "La ley de Herodes", 1),
        ("Best Supporting Actress", "Isela Vega", "La ley de Herodes", 1),
        ("Best Screenplay", "Luis Estrada", "La ley de Herodes", 1),
        ("Best Cinematography", "Norman Christianson", "La ley de Herodes", 1),
    ],
    2000: [
        ("Best Picture", "Todo el poder", "Todo el poder", 1),
        ("Best Director", "Fernando Sariñana", "Todo el poder", 1),
        ("Best Actor", "Demián Bichir", "Todo el poder", 1),
        ("Best Actress", "Cecilia Suárez", "Todo el poder", 1),
        ("Best Supporting Actor", "Luis Felipe Tovar", "Todo el poder", 1),
        ("Best Supporting Actress", "Dolores Heredia", "Todo el poder", 1),
        ("Best Screenplay", "Fernando Sariñana", "Todo el poder", 1),
        ("Best Cinematography", "Xavier Pérez Grobet", "Todo el poder", 1),
    ],
    1999: [
        ("Best Picture", "Central do Brasil", "Central do Brasil", 1),
        ("Best Director", "Walter Salles", "Central do Brasil", 1),
        ("Best Actor", "Fernanda Montenegro", "Central do Brasil", 1),
        ("Best Actress", "Fernanda Montenegro", "Central do Brasil", 1),
        ("Best Supporting Actor", "Vinicius de Oliveira", "Central do Brasil", 1),
        ("Best Supporting Actress", "Marilia Pera", "Central do Brasil", 1),
        ("Best Screenplay", "Marcos Bernstein", "Central do Brasil", 1),
        ("Best Cinematography", "Walter Carvalho", "Central do Brasil", 1),
    ],
    1998: [
        ("Best Picture", "El evangelio de las maravillas", "El evangelio de las maravillas", 1),
        ("Best Director", "Arturo Ripstein", "El evangelio de las maravillas", 1),
        ("Best Actor", "Ernesto Gómez Cruz", "El evangelio de las maravillas", 1),
        ("Best Actress", "Katy Jurado", "El evangelio de las maravillas", 1),
        ("Best Supporting Actor", "Bruno Bichir", "El evangelio de las maravillas", 1),
        ("Best Supporting Actress", "Delia Casanova", "El evangelio de las maravillas", 1),
        ("Best Screenplay", "Paz Alicia Garciadiego", "El evangelio de las maravillas", 1),
        ("Best Cinematography", "Guillermo Granillo", "El evangelio de las maravillas", 1),
    ],
    1997: [
        ("Best Picture", "Cilantro y Perejil", "Cilantro y Perejil", 1),
        ("Best Director", "Rafael Montero", "Cilantro y Perejil", 1),
        ("Best Actor", "Ernesto Laguardia", "Cilantro y Perejil", 1),
        ("Best Actress", "Diana Bracho", "Cilantro y Perejil", 1),
        ("Best Supporting Actor", "Bruno Bichir", "Cilantro y Perejil", 1),
        ("Best Supporting Actress", "Claudia Ramírez", "Cilantro y Perejil", 1),
        ("Best Screenplay", "Rafael Montero", "Cilantro y Perejil", 1),
        ("Best Cinematography", "Federico Martínez Terrazas", "Cilantro y Perejil", 1),
    ],
    1996: [
        ("Best Picture", "El callejón de los milagros", "El callejón de los milagros", 1),
        ("Best Director", "Jorge Fons", "El callejón de los milagros", 1),
        ("Best Actor", "Ernesto Gómez Cruz", "El callejón de los milagros", 1),
        ("Best Actress", "Salma Hayek", "El callejón de los milagros", 1),
        ("Best Supporting Actor", "Bruno Bichir", "El callejón de los milagros", 1),
        ("Best Supporting Actress", "María Rojo", "El callejón de los milagros", 1),
        ("Best Screenplay", "Vicente Leñero", "El callejón de los milagros", 1),
        ("Best Cinematography", "Carlos Marcovich", "El callejón de los milagros", 1),
    ],
    1995: [
        ("Best Picture", "Cronos", "Cronos", 1),
        ("Best Director", "Guillermo del Toro", "Cronos", 1),
        ("Best Actor", "Federico Luppi", "Cronos", 1),
        ("Best Actress", "Tamara Shanath", "Cronos", 1),
        ("Best Supporting Actor", "Ron Perlman", "Cronos", 1),
        ("Best Supporting Actress", "Margarita Isabel", "Cronos", 1),
        ("Best Screenplay", "Guillermo del Toro", "Cronos", 1),
        ("Best Cinematography", "Guillermo Navarro", "Cronos", 1),
    ],
    1994: [
        ("Best Picture", "Como agua para chocolate", "Como agua para chocolate", 1),
        ("Best Director", "Alfonso Arau", "Como agua para chocolate", 1),
        ("Best Actor", "Alfredo Macías", "Como agua para chocolate", 1),
        ("Best Actress", "Lumi Cavazos", "Como agua para chocolate", 1),
        ("Best Supporting Actor", "Mario Iván Martínez", "Como agua para chocolate", 1),
        ("Best Supporting Actress", "Regina Torné", "Como agua para chocolate", 1),
        ("Best Screenplay", "Laura Esquivel", "Como agua para chocolate", 1),
        ("Best Cinematography", "Emmanuel Lubezki", "Como agua para chocolate", 1),
    ],
    1993: [
        ("Best Picture", "Sólo con tu pareja", "Sólo con tu pareja", 1),
        ("Best Director", "Alfonso Cuarón", "Sólo con tu pareja", 1),
        ("Best Actor", "Daniel Giménez Cacho", "Sólo con tu pareja", 1),
        ("Best Actress", "Claudia Ramírez", "Sólo con tu pareja", 1),
        ("Best Supporting Actor", "Luis de Icaza", "Sólo con tu pareja", 1),
        ("Best Supporting Actress", "Astrid Hadad", "Sólo con tu pareja", 1),
        ("Best Screenplay", "Alfonso Cuarón", "Sólo con tu pareja", 1),
        ("Best Cinematography", "Emmanuel Lubezki", "Sólo con tu pareja", 1),
    ],
    1992: [
        ("Best Picture", "Rojo amanecer", "Rojo amanecer", 1),
        ("Best Director", "Jorge Fons", "Rojo amanecer", 1),
        ("Best Actor", "Héctor Bonilla", "Rojo amanecer", 1),
        ("Best Actress", "María Rojo", "Rojo amanecer", 1),
        ("Best Supporting Actor", "Eduardo Palomo", "Rojo amanecer", 1),
        ("Best Supporting Actress", "Leticia Lupercio", "Rojo amanecer", 1),
        ("Best Screenplay", "Xavier Robles", "Rojo amanecer", 1),
        ("Best Cinematography", "Miguel Garzón", "Rojo amanecer", 1),
    ],
    1991: [
        ("Best Picture", "Ángel de fuego", "Ángel de fuego", 1),
        ("Best Director", "Dana Rotberg", "Ángel de fuego", 1),
        ("Best Actor", "Roberto Sosa", "Ángel de fuego", 1),
        ("Best Actress", "Evangelina Sosa", "Ángel de fuego", 1),
        ("Best Supporting Actor", "Pedro Armendáriz Jr.", "Ángel de fuego", 1),
        ("Best Supporting Actress", "Dolores Beristáin", "Ángel de fuego", 1),
        ("Best Screenplay", "Dana Rotberg", "Ángel de fuego", 1),
        ("Best Cinematography", "Rodrigo Prieto", "Ángel de fuego", 1),
    ],
    1990: [
        ("Best Picture", "Rojo amanecer", "Rojo amanecer", 1),
        ("Best Director", "Jorge Fons", "Rojo amanecer", 1),
        ("Best Actor", "Héctor Bonilla", "Rojo amanecer", 1),
        ("Best Actress", "María Rojo", "Rojo amanecer", 1),
        ("Best Supporting Actor", "Ernesto Gómez Cruz", "Rojo amanecer", 1),
        ("Best Supporting Actress", "Adriana Roel", "Rojo amanecer", 1),
        ("Best Screenplay", "Xavier Robles", "Rojo amanecer", 1),
        ("Best Cinematography", "Miguel Garzón", "Rojo amanecer", 1),
    ],
    1989: [
        ("Best Picture", "El cometa", "El cometa", 1),
        ("Best Director", "María Novaro", "Lola", 1),
        ("Best Actor", "José Alonso", "El cometa", 1),
        ("Best Actress", "Leticia Perdigón", "Lola", 1),
        ("Best Supporting Actor", "Pedro Armendáriz Jr.", "El cometa", 1),
        ("Best Supporting Actress", "Margarita Isabel", "El cometa", 1),
        ("Best Screenplay", "Joaquín Bestard", "El cometa", 1),
        ("Best Cinematography", "Rodrigo Prieto", "El cometa", 1),
    ],
    1988: [
        ("Best Picture", "Lo del César", "Lo del César", 1),
        ("Best Director", "Arturo Ripstein", "Principio y Fin", 1),
        ("Best Actor", "Gonzalo Vega", "Lo del César", 1),
        ("Best Actress", "Dolores Heredia", "Lo del César", 1),
        ("Best Supporting Actor", "Salvador Sánchez", "Lo del César", 1),
        ("Best Supporting Actress", "Blanca Guerra", "Lo del César", 1),
        ("Best Screenplay", "Arturo Ripstein", "Lo del César", 1),
        ("Best Cinematography", "Guillermo Granillo", "Lo del César", 1),
    ],
    1987: [
        ("Best Picture", "Frida, naturaleza viva", "Frida, naturaleza viva", 1),
        ("Best Director", "Paul Leduc", "Frida, naturaleza viva", 1),
        ("Best Actor", "Héctor Ortega", "Frida, naturaleza viva", 1),
        ("Best Actress", "Ofelia Medina", "Frida, naturaleza viva", 1),
        ("Best Supporting Actor", "Claudio Brook", "Frida, naturaleza viva", 1),
        ("Best Supporting Actress", "Max Kerlow", "Frida, naturaleza viva", 1),
        ("Best Screenplay", "Paul Leduc", "Frida, naturaleza viva", 1),
        ("Best Cinematography", "Ángel Goded", "Frida, naturaleza viva", 1),
    ],
    1986: [
        ("Best Picture", "El imperio de la fortuna", "El imperio de la fortuna", 1),
        ("Best Director", "Arturo Ripstein", "El imperio de la fortuna", 1),
        ("Best Actor", "Ernesto Gómez Cruz", "El imperio de la fortuna", 1),
        ("Best Actress", "Blanca Guerra", "El imperio de la fortuna", 1),
        ("Best Supporting Actor", "Alejandro Parodi", "El imperio de la fortuna", 1),
        ("Best Supporting Actress", "Zaide Silvia Gutiérrez", "El imperio de la fortuna", 1),
        ("Best Screenplay", "Paz Alicia Garciadiego", "El imperio de la fortuna", 1),
        ("Best Cinematography", "Ángel Goded", "El imperio de la fortuna", 1),
    ],
    1985: [
        ("Best Picture", "Bajo el volcán", "Bajo el volcán", 1),
        ("Best Director", "John Huston", "Bajo el volcán", 1),
        ("Best Actor", "Albert Finney", "Bajo el volcán", 1),
        ("Best Actress", "Jacqueline Bisset", "Bajo el volcán", 1),
        ("Best Supporting Actor", "Arnoldo Martínez", "Bajo el volcán", 1),
        ("Best Supporting Actress", "Katy Jurado", "Bajo el volcán", 1),
        ("Best Screenplay", "Guy Gallo", "Bajo el volcán", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Bajo el volcán", 1),
    ],
    1984: [
        ("Best Picture", "El norte", "El norte", 1),
        ("Best Director", "Gregory Nava", "El norte", 1),
        ("Best Actor", "David Villalpando", "El norte", 1),
        ("Best Actress", "Zaide Silvia Gutiérrez", "El norte", 1),
        ("Best Supporting Actor", "Ernesto Cruz", "El norte", 1),
        ("Best Supporting Actress", "Lupe Ontiveros", "El norte", 1),
        ("Best Screenplay", "Gregory Nava", "El norte", 1),
        ("Best Cinematography", "James Glennon", "El norte", 1),
    ],
    1983: [
        ("Best Picture", "Eréndira", "Eréndira", 1),
        ("Best Director", "Ruy Guerra", "Eréndira", 1),
        ("Best Actor", "Pedro Armendáriz Jr.", "Eréndira", 1),
        ("Best Actress", "Irene Papas", "Eréndira", 1),
        ("Best Supporting Actor", "Michel Lonsdale", "Eréndira", 1),
        ("Best Supporting Actress", "Rufus", "Eréndira", 1),
        ("Best Screenplay", "Gabriel García Márquez", "Eréndira", 1),
        ("Best Cinematography", "Denys Clerval", "Eréndira", 1),
    ],
    1982: [
        ("Best Picture", "Canoa", "Canoa", 1),
        ("Best Director", "Felipe Cazals", "Canoa", 1),
        ("Best Actor", "Ernesto Gómez Cruz", "Canoa", 1),
        ("Best Actress", "María Rojo", "Canoa", 1),
        ("Best Supporting Actor", "Salvador Sánchez", "Canoa", 1),
        ("Best Supporting Actress", "Delia Casanova", "Canoa", 1),
        ("Best Screenplay", "Tomás Pérez Turrent", "Canoa", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "Canoa", 1),
    ],
    1981: [
        ("Best Picture", "El apando", "El apando", 1),
        ("Best Director", "Felipe Cazals", "El apando", 1),
        ("Best Actor", "Salvador Sánchez", "El apando", 1),
        ("Best Actress", "María Rojo", "El apando", 1),
        ("Best Supporting Actor", "Manuel Ojeda", "El apando", 1),
        ("Best Supporting Actress", "Rosario Gálvez", "El apando", 1),
        ("Best Screenplay", "José Revueltas", "El apando", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "El apando", 1),
    ],
    1980: [
        ("Best Picture", "El castor furioso", "El castor furioso", 1),
        ("Best Director", "Emilio Fernández", "El castor furioso", 1),
        ("Best Actor", "Jorge Martínez de Hoyos", "El castor furioso", 1),
        ("Best Actress", "Katy Jurado", "El castor furioso", 1),
        ("Best Supporting Actor", "Wolf Ruvinskis", "El castor furioso", 1),
        ("Best Supporting Actress", "Columba Domínguez", "El castor furioso", 1),
        ("Best Screenplay", "Emilio Fernández", "El castor furioso", 1),
        ("Best Cinematography", "Gabriel Figueroa", "El castor furioso", 1),
    ],
    1979: [
        ("Best Picture", "Maten al León", "Maten al León", 1),
        ("Best Director", "José Estrada", "Maten al León", 1),
        ("Best Actor", "Gonzalo Vega", "Maten al León", 1),
        ("Best Actress", "Sonia Infante", "Maten al León", 1),
        ("Best Supporting Actor", "Héctor Ortega", "Maten al León", 1),
        ("Best Supporting Actress", "Meche Carreño", "Maten al León", 1),
        ("Best Screenplay", "Jorge Ibargüengoitia", "Maten al León", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "Maten al León", 1),
    ],
    1978: [
        ("Best Picture", "El castillo de la pureza", "El castillo de la pureza", 1),
        ("Best Director", "Arturo Ripstein", "El castillo de la pureza", 1),
        ("Best Actor", "Claudio Brook", "El castillo de la pureza", 1),
        ("Best Actress", "Rita Macedo", "El castillo de la pureza", 1),
        ("Best Supporting Actor", "Arturo Beristáin", "El castillo de la pureza", 1),
        ("Best Supporting Actress", "Diana Bracho", "El castillo de la pureza", 1),
        ("Best Screenplay", "José Emilio Pacheco", "El castillo de la pureza", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "El castillo de la pureza", 1),
    ],
    1977: [
        ("Best Picture", "Canoa", "Canoa", 1),
        ("Best Director", "Felipe Cazals", "Canoa", 1),
        ("Best Actor", "Ernesto Gómez Cruz", "Canoa", 1),
        ("Best Actress", "Dolores Beristáin", "Canoa", 1),
        ("Best Supporting Actor", "Salvador Sánchez", "Canoa", 1),
        ("Best Supporting Actress", "Delia Casanova", "Canoa", 1),
        ("Best Screenplay", "Tomás Pérez Turrent", "Canoa", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "Canoa", 1),
    ],
    1976: [
        ("Best Picture", "El Santo Oficio", "El Santo Oficio", 1),
        ("Best Director", "Arturo Ripstein", "El Santo Oficio", 1),
        ("Best Actor", "Claudio Brook", "El Santo Oficio", 1),
        ("Best Actress", "Diana Bracho", "El Santo Oficio", 1),
        ("Best Supporting Actor", "Wolf Ruvinskis", "El Santo Oficio", 1),
        ("Best Supporting Actress", "Malena Doria", "El Santo Oficio", 1),
        ("Best Screenplay", "Tomás Pérez Turrent", "El Santo Oficio", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "El Santo Oficio", 1),
    ],
    1975: [
        ("Best Picture", "El profeta Mimí", "El profeta Mimí", 1),
        ("Best Director", "Luis Alcoriza", "El profeta Mimí", 1),
        ("Best Actor", "David Reynoso", "El profeta Mimí", 1),
        ("Best Actress", "Pilar Pellicer", "El profeta Mimí", 1),
        ("Best Supporting Actor", "Arturo Castro", "El profeta Mimí", 1),
        ("Best Supporting Actress", "Ofelia Guilmáin", "El profeta Mimí", 1),
        ("Best Screenplay", "Luis Alcoriza", "El profeta Mimí", 1),
        ("Best Cinematography", "Gabriel Figueroa", "El profeta Mimí", 1),
    ],
    1974: [
        ("Best Picture", "El apando", "El apando", 1),
        ("Best Director", "Felipe Cazals", "El apando", 1),
        ("Best Actor", "Salvador Sánchez", "El apando", 1),
        ("Best Actress", "María Rojo", "El apando", 1),
        ("Best Supporting Actor", "Manuel Ojeda", "El apando", 1),
        ("Best Supporting Actress", "Rosario Gálvez", "El apando", 1),
        ("Best Screenplay", "José Revueltas", "El apando", 1),
        ("Best Cinematography", "Alex Phillips Jr.", "El apando", 1),
    ],
    1973: [
        ("Best Picture", "El topo", "El topo", 1),
        ("Best Director", "Alejandro Jodorowsky", "El topo", 1),
        ("Best Actor", "Alejandro Jodorowsky", "El topo", 1),
        ("Best Actress", "Mara Lorenzio", "El topo", 1),
        ("Best Supporting Actor", "Robert John", "El topo", 1),
        ("Best Supporting Actress", "Paula Romo", "El topo", 1),
        ("Best Screenplay", "Alejandro Jodorowsky", "El topo", 1),
        ("Best Cinematography", "Rafael Corkidi", "El topo", 1),
    ],
    1972: [
        ("Best Picture", "Macario", "Macario", 1),
        ("Best Director", "Roberto Gavaldón", "Macario", 1),
        ("Best Actor", "Ignacio López Tarso", "Macario", 1),
        ("Best Actress", "Pina Pellicer", "Macario", 1),
        ("Best Supporting Actor", "Enrique Lucero", "Macario", 1),
        ("Best Supporting Actress", "Consuelo Frank", "Macario", 1),
        ("Best Screenplay", "Emilio Carballido", "Macario", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Macario", 1),
    ],
    1971: [
        ("Best Picture", "El jardín de la tía Isabel", "El jardín de la tía Isabel", 1),
        ("Best Director", "Carlos Velo", "El jardín de la tía Isabel", 1),
        ("Best Actor", "Jorge Martínez de Hoyos", "El jardín de la tía Isabel", 1),
        ("Best Actress", "Patricia Morán", "El jardín de la tía Isabel", 1),
        ("Best Supporting Actor", "Claudio Brook", "El jardín de la tía Isabel", 1),
        ("Best Supporting Actress", "Pilar Pellicer", "El jardín de la tía Isabel", 1),
        ("Best Screenplay", "Carlos Velo", "El jardín de la tía Isabel", 1),
        ("Best Cinematography", "Gabriel Figueroa", "El jardín de la tía Isabel", 1),
    ],
    1970: [
        ("Best Picture", "Río Escondido", "Río Escondido", 1),
        ("Best Director", "Emilio Fernández", "Río Escondido", 1),
        ("Best Actor", "Carlos López Moctezuma", "Río Escondido", 1),
        ("Best Actress", "María Félix", "Río Escondido", 1),
        ("Best Supporting Actor", "Fernando Fernández", "Río Escondido", 1),
        ("Best Supporting Actress", "Columba Domínguez", "Río Escondido", 1),
        ("Best Screenplay", "Emilio Fernández", "Río Escondido", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Río Escondido", 1),
    ],
    1969: [
        ("Best Picture", "Simón del desierto", "Simón del desierto", 1),
        ("Best Director", "Luis Buñuel", "Simón del desierto", 1),
        ("Best Actor", "Claudio Brook", "Simón del desierto", 1),
        ("Best Actress", "Silvia Pinal", "Simón del desierto", 1),
        ("Best Supporting Actor", "Hortensia Santoveña", "Simón del desierto", 1),
        ("Best Supporting Actress", "Enrique Álvarez Félix", "Simón del desierto", 1),
        ("Best Screenplay", "Luis Buñuel", "Simón del desierto", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Simón del desierto", 1),
    ],
    1968: [
        ("Best Picture", "El ángel exterminador", "El ángel exterminador", 1),
        ("Best Director", "Luis Buñuel", "El ángel exterminador", 1),
        ("Best Actor", "Enrique Rambal", "El ángel exterminador", 1),
        ("Best Actress", "Silvia Pinal", "El ángel exterminador", 1),
        ("Best Supporting Actor", "Claudio Brook", "El ángel exterminador", 1),
        ("Best Supporting Actress", "Jacqueline Andere", "El ángel exterminador", 1),
        ("Best Screenplay", "Luis Buñuel", "El ángel exterminador", 1),
        ("Best Cinematography", "Gabriel Figueroa", "El ángel exterminador", 1),
    ],
    1967: [
        ("Best Picture", "El gallo de oro", "El gallo de oro", 1),
        ("Best Director", "Roberto Gavaldón", "El gallo de oro", 1),
        ("Best Actor", "Ignacio López Tarso", "El gallo de oro", 1),
        ("Best Actress", "Lucha Villa", "El gallo de oro", 1),
        ("Best Supporting Actor", "Narciso Busquets", "El gallo de oro", 1),
        ("Best Supporting Actress", "Columba Domínguez", "El gallo de oro", 1),
        ("Best Screenplay", "Gabriel García Márquez", "El gallo de oro", 1),
        ("Best Cinematography", "Gabriel Figueroa", "El gallo de oro", 1),
    ],
    1966: [
        ("Best Picture", "Los olvidados", "Los olvidados", 1),
        ("Best Director", "Luis Buñuel", "Los olvidados", 1),
        ("Best Actor", "Alfonso Mejía", "Los olvidados", 1),
        ("Best Actress", "Estela Inda", "Los olvidados", 1),
        ("Best Supporting Actor", "Roberto Cobo", "Los olvidados", 1),
        ("Best Supporting Actress", "Alma Delia Fuentes", "Los olvidados", 1),
        ("Best Screenplay", "Luis Buñuel", "Los olvidados", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Los olvidados", 1),
    ],
    1965: [
        ("Best Picture", "La ilusión viaja en tranvía", "La ilusión viaja en tranvía", 1),
        ("Best Director", "Luis Buñuel", "La ilusión viaja en tranvía", 1),
        ("Best Actor", "Lilia Prado", "La ilusión viaja en tranvía", 1),
        ("Best Actress", "Lilia Prado", "La ilusión viaja en tranvía", 1),
        ("Best Supporting Actor", "Carlos Navarro", "La ilusión viaja en tranvía", 1),
        ("Best Supporting Actress", "Begoña Palacios", "La ilusión viaja en tranvía", 1),
        ("Best Screenplay", "Luis Buñuel", "La ilusión viaja en tranvía", 1),
        ("Best Cinematography", "Gabriel Figueroa", "La ilusión viaja en tranvía", 1),
    ],
    1964: [
        ("Best Picture", "Los olvidados", "Los olvidados", 1),
        ("Best Director", "Luis Buñuel", "Los olvidados", 1),
        ("Best Actor", "Alfonso Mejía", "Los olvidados", 1),
        ("Best Actress", "Estela Inda", "Los olvidados", 1),
        ("Best Supporting Actor", "Roberto Cobo", "Los olvidados", 1),
        ("Best Supporting Actress", "Alma Delia Fuentes", "Los olvidados", 1),
        ("Best Screenplay", "Luis Buñuel", "Los olvidados", 1),
        ("Best Cinematography", "Gabriel Figueroa", "Los olvidados", 1),
    ],
    1963: [
        ("Best Picture", "Viridiana", "Viridiana", 1),
        ("Best Director", "Luis Buñuel", "Viridiana", 1),
        ("Best Actor", "Fernando Rey", "Viridiana", 1),
        ("Best Actress", "Silvia Pinal", "Viridiana", 1),
        ("Best Supporting Actor", "Francisco Rabal", "Viridiana", 1),
        ("Best Supporting Actress", "Margarita Lozano", "Viridiana", 1),
        ("Best Screenplay", "Luis Buñuel", "Viridiana", 1),
        ("Best Cinematography", "José F. Aguayo", "Viridiana", 1),
    ],
}

def main():
    print(f"Building Diosas de Plata CSV with real historical data...")
    rows = []
    for year in sorted(KNOWN_WINNERS.keys()):
        for (cat, nominee, film, won) in KNOWN_WINNERS[year]:
            rows.append({
                "year": year,
                "ceremony": CEREMONY_NAME,
                "category": cat,
                "nominee": nominee,
                "film": film,
                "won": won,
            })

    out = OUTPUT_FILE
    with open(out, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["year", "ceremony", "category", "nominee", "film", "won"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"Saved {len(rows)} rows to {out}")
    print(f"Years covered: {min(KNOWN_WINNERS)} – {max(KNOWN_WINNERS)}")
    print(f"Editions: {len(KNOWN_WINNERS)}")

if __name__ == "__main__":
    main()
